parameters:
  name: RelativePathToTerraformFiles
  type: string

stages:
  - stage: Build
    variables:
      terraformTargetPath: $(Build.SourcesDirectory)/$(RelativePathToTerraformFiles)
    displayName: "Build"
    jobs:
      - job: PublishTerraformArtifact
        workspace:
          clean: all
        displayName: "Publish Terraform Artifact"
        steps:
          - task: PublishPipelineArtifact@1
            displayName: "Publish Terraform Artifact"
            inputs:
              targetPath: $(terraformTargetPath)
              artifact: TerraformArtifact
              publishLocation: "pipeline"