parameters:
  name: TerraformPathSection
  type: string

stages:
  - stage: Build
    variables:
      terraformTargetPath: $(Build.SourcesDirectory)/$(TerraformPathSection)
    displayName: "Build"
    jobs:
      - job: PublishTerraformArtifact
        workspace:
          clean: all
        displayName: "Publish Terraform Artifact"
        steps:
          - task: PowerShell@2
            name: diagnostics
            displayName: "Diagnostic Information"
            inputs:
              targetType: inline
              script: |
                Write-Host "terraformTargetPath: $(terraformTargetPath)"
                Write-Host "Content of terraformTargetPath directory"
                Get-ChildItem $(terraformTargetPath)
            
          - task: PublishPipelineArtifact@1
            displayName: "Publish Terraform Artifact"
            inputs:
              targetPath: $(terraformTargetPath)
              artifact: TerraformArtifact
              publishLocation: "pipeline"