parameters:
  - name: relativePathToTerraformFiles
    type: string

stages:
  - stage: Checks
    dependsOn: "Build"
    variables:
      terraformTargetPath: $(Build.SourcesDirectory)/${{ parameters.relativePathToTerraformFiles }}
    displayName: "Checks"
    jobs:
      - job: Trivy
        workspace:
          clean: all
        steps:
          - checkout: self

          - template: trivy/trivy-pipelines.yml@UKHOTemplates
            parameters:
              WorkingDirectory: $(terraformTargetPath)