parameters:
  - name: environment
    type: string
    default: 'dev'
  - name: condition
    type: string
    default: 'succeeded()'
  - name: dependsOn
    type: object
    default: { }
  - name: tfStateBlobName
    type: string

stages:
  - stage: Deploy_${{ parameters.environment }}
    displayName: "Deploy ${{ parameters.environment }}"
    condition: ${{parameters.condition}}
    dependsOn:
      - ${{ each dependsOnThis in parameters.dependsOn }}:
          - ${{ dependsOnThis }}
    jobs:
      - template: template.yml@GatedInfrastructureDeploy
        parameters:
          AzDOEnvironmentName: ""
          TFStateResourceGroupName: ""
          TFStateStorageAccountName: ""
          TFStateContainerName: ""
          TFStateBlobName: ${{ parameters.tfStateBlobName }}
          TerraformWorkspace: ${{ parameters.environment }}
          TerraformArtifactConfigRelativePath: "/"
          TerraformArtifact: "TerraformArtifact"
          TerraformContainer: TerraformContainer
          VariablesTemplateRelativePath: /pipeline/infrastructure-pipeline-templates/vars-${{ parameters.environment }}-deploy.yml
          TerraformVariableMappings:
            ARM_CLIENT_ID: $(TERRAFORM-CLIENT-ID)
            ARM_CLIENT_SECRET: $(TERRAFORM-CLIENT-SECRET)
            ARM_TENANT_ID: $(TERRAFORM-TENANT-ID)
            ARM_SUBSCRIPTION_ID: $(TERRAFORM-SUBSCRIPTION-ID)
            TF_VAR_environment: ${{ parameters.environment }}