parameters:
  - name: Environment
    type: string
    default: 'dev'
  - name: Condition
    type: string
    default: 'succeeded()'
  - name: DependsOn
    type: object
    default: { }
  - name: TFStateBlobName
    type: string
  - name: TFStateResourceGroupName
    type: string
  - name: TFStateStorageAccountName
    type: string
  - name: TFStateContainerName
    type: string
  - name: VariablesTemplateRelativePath
    type: string
  - name: TerraformVariableMappings
    type: object

stages:
  - stage: Deploy_${{ parameters.Environment }}
    displayName: "Deploy ${{ parameters.Environment }}"
    condition: ${{ parameters.Condition }}
    dependsOn:
      - ${{ each dependsOnThis in parameters.DependsOn }}:
          - ${{ dependsOnThis }}
    jobs:
      - template: template.yml@GatedInfrastructureDeploy
        parameters:
          AzDOEnvironmentName: ${{ parameters.Environment }}
          TFStateResourceGroupName: ${{ parameters.TFStateResourceGroup }}
          TFStateStorageAccountName: ${{ parameters.TFStateStorageAccountName }}
          TFStateContainerName: ${{ parameters.TFStateContainerName }}
          TFStateBlobName: ${{ parameters.TFStateBlobName }}
          TerraformWorkspace: ${{ parameters.Environment }}
          TerraformArtifactConfigRelativePath: "/"
          TerraformArtifact: "TerraformArtifact" # Hardcoded until it doesn't need to be
          TerraformContainer: TerraformContainer
          VariablesTemplateRelativePath: ${{ parameters.VariablesTemplateRelativePath }}
          TerraformVariableMappings:
            ${{each TerraformVariableMappings in parameters.TerraformVariableMappings}}:
              ${{TerraformVariableMappings.Key}}: ${{TerraformVariableMappings.Value}}